name: Build VirtualApp Project (Unsigned)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:        # اجازه اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت کد منبع
        uses: actions/checkout@v4

      - name: نصب JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: تنظیم مجوز Gradle Wrapper
        run: chmod +x gradlew

      # بیلد گرفتن از پروژه (بدون نیاز به امضا)
      - name: بیلد پروژه
        run: ./gradlew assembleDebug

      # آپلود همه فایل‌های APK ساخته شده
      - name: آپلود APKها
        uses: actions/upload-artifact@v4
        with:
          name: VirtualApp-Debug-APKs
          path: |
            */build/outputs/apk/**/*.apk
            !*/build/outputs/apk/**/*-unsigned.apk
            !*/build/outputs/apk/**/*-unaligned.apk
